### ISSUE TITLE
ert-plugin generates invalid fingerprints

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/ert-plugin#1]
ert-plugin v0.0.6-2c316c generates invalid fingerprints.

It produces something like this:

```
instance_groups:
- name: cloud_controller-partition
  jobs:
  - name: cloud_controller_ng
    properties:
      app_ssh:
        host_key_fingerprint: "hyqgbedosdn7886qvxs90"
```

But should instead produce the fingerprint of the host pub key, like:

```
instance_groups:
- name: cloud_controller-partition
  jobs:
  - name: cloud_controller_ng
    properties:
      app_ssh:
        host_key_fingerprint: "ad:6a:47:ca:8b:ee:ef:25:2a:78:04:f2:12:35:04:a2"
```

**Comment by xchapter7x** [comment]
this should be fixed : https://github.com/enaml-ops/ert-plugin/releases/tag/v0.0.10

**Comment by sushiandbeer** [comment]
v0.0.10 is still generating invalid fingerprints.

My deployment manifest had `host_key_fingerprint: 5b:15:2f:99:b2:44:ab:4b:21:e5:5e:8e:a3:db:28:4f`

```
$ cf ssh app1
FAILED
Error opening SSH connection: ssh: handshake failed: Host key verification failed.
```

To resolve the issue, I saved the private key from the manifest to a file `host_key.key` and removed leading whitespace:

```
  - name: ssh_proxy
    release: diego
    properties:
      diego:
        ssh_proxy:
          host_key: |
            -----BEGIN RSA PRIVATE KEY-----
            ...
```

And then extracted the public key and generated the public key fingerprint.

```
$ ssh-keygen -f host_key.key > host_key.pub
$ ssh-keygen -lf host_key.pub -E md5 | cut -d ' ' -f2 | sed 's/MD5://g'
05:43:75:3d:0f:8d:4e:1c:18:8e:7e:fc:09:0f:57:42
```

I replaced the value of `host_key_fingerprint` with this new fingerprint and redeployed.  `cf ssh my app` now works.

```
$ cf ssh myapp
vcap@f688ed9a-91b3-43d8-57c7-f285167f0144:~$
```
