### ISSUE TITLE
ert-plugin should enable cf auth for diego ssh

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/ert-plugin#2]
Expected config:

```
  - name: ssh_proxy
    release: diego
    properties:
      diego:
        ssh_proxy:
          enable_cf_auth: true
```

Actual config:

```
  - name: ssh_proxy
    release: diego
    properties:
      diego:
        ssh_proxy:
          enable_cf_auth: false
```

**Comment by xchapter7x** [comment]
have you tried setting the `allow-app-ssh-access` flag?

**Comment by sushiandbeer** [comment]
Even with the latest version, it looks like it's not observing the `allow-app-ssh-access` key set in vault:

```
$ vault read -field=allow-app-ssh-access secret/cf-sandbox-b-props
true
```

The generated manifest shows:

```
- name: cloud_controller-partition
  ...
  jobs:
  - name: cloud_controller_ng
    ...
    properties:
      app_ssh:
        host_key_fingerprint: xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
      cc:
        allow_app_ssh_access: false
  - name: ssh_proxy
    release: diego
    properties:
      diego:
      ...
        enable_cf_auth: false
```
