### ISSUE TITLE
Some acceptance tests properties are nested too deeply

### ISSUE THREAD

**Issue by sushiandbeer** [enaml-ops/ert-plugin#3]
Acceptance tests properties should not be a subgroup of cloud_controller props:

Expected config
```
- name: acceptance-tests
  instances: 1
  vm_type: small
  stemcell: trusty
  azs:
  - az1
  networks:
  - name: private
  jobs:
  - name: acceptance-tests
    release: cf
    properties:
      acceptance_tests:
        admin_password: aasiuonaslicun2sacd
        admin_user: admin
        api: https://api.sys.10.10.10.10.xip.io
        apps_domain: apps.10.10.10.10.xip.io
        skip_ssl_validation: true
        system_domain: sys.10.10.10.10.xip.io
  update:
    max_in_flight: 1
  lifecycle: errand
```

Actual config:

```
- name: acceptance-tests
  instances: 1
  vm_type: small
  stemcell: trusty
  azs:
  - az1
  networks:
  - name: private
  jobs:
  - name: acceptance-tests
    release: cf
    properties:
      acceptance_tests:
        cloud_controller:
          admin_password: aasiuonaslicun2sacd
          admin_user: admin
          api: https://api.sys.10.10.10.10.xip.io
          apps_domain: apps.10.10.10.10.xip.io
        skip_ssl_validation: true
        system_domain: sys.10.10.10.10.xip.io
  update:
    max_in_flight: 1
  lifecycle: errand
```
